version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    container_name: route-planning-db
    restart: always
    environment:
      POSTGRES_DB: route_planning_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data